name: Push to EC2 (ec2-ci-main.yml)
run-name: ${{ github.actor }} is pushing to EC2 from ${{ github.repository }}
on:
  push:
    branches:
    - main
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: make build-test
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: danOO7/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          # workaround for nvm https://github.com/appleboy/ssh-action/issues/70
          # export NVM_DIR="$HOME/.nvm"
          # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          script: |
            eval `ssh-agent` &&\
            ssh-add ~/.ssh/ci_rsa &&\
            cd ${{ github.repository }} && \
            pwd && \
            git checkout ${{ github.ref_name }} && \
            git pull && \ 
            make release && \
            pm2 restart --name=caml dist/app.js -i 2
